# KanaEventManager Add-on to KanaBungeeTP
# KanaEventManager Version 2.3.0
# KanaBungeeTP required Version 2.2.2 or above (compatible 2.0.1 but not recommended)

# If database doesn't work plugin will be stop working unexpectedly

database:
  host: "127.0.0.1"
  user: ""
  password: ""
  database: ""
  port: "3306"

  tables:
    event: "KEM_event"
    score: "KEM_score"

# Server configuration for BungeeCord (specifies the bungee's config.yml server's name)

BungeeCord:
  lobbyServerName: "lobby"
  eventServerName: "event"

# Auto spawn point at connexion
SpawnPoint:
  locX: 0
  locY: 0
  locZ: 0
  pitch: 0
  yaw: 0

# Auto check score table (second)
AutoCheckScoreIntervall: 60

# Broadcast for event
Broadcast: "&9[{isBetaEvent}EVENT {EventName}] &6{Broadcast} \n&epour participer faîtes &a/bmenu"
SingleWinBroadcast: "&9[EVENT {EventName}] &eBravo à {PlayerName} qui a gagné l'event et remporte {rewards}"
MultipleWinBroadcast: "&9[EVENT {EventName}] &eBravo à {PlayersList} qui ont gagné l'event et remportent {rewards}"

# Specify the word that say event is beta-testing event
BetaEventWord: "Bêta Testing-"

# Specify the link word between multiple rewards
RewardsLinkWord: "et"

# Gave reward after rewardsPing seconds
rewardsPing: 1

# rewards objects
rewards:

  cle1:
    command: cc give p Niveau1 {amount} {playerName}
    displayName: Clé(s) de niveau 1
  cle2:
    command: cc give p Niveau2 {amount} {playerName}
    displayName: Clé(s) de niveau 2
  cle3:
    command: cc give p Niveau3 {amount} {playerName}
    displayName: Clé(s) de niveau 3
  money:
    command: money give {playerName} {amount}
    displayName: Hc