
# KanaEventManager Add-on to KanaBungeeTP
# KanaEventManager Version 2.1.0
# KanaBungeeTP required Version 2.0.1 or above

# If database doesn't work plugin will be disable

database:
  host: "127.0.0.1"
  user: "root"
  password: "sqldevtest"
  database: "test"
  port: "3306"

  tables:
    event: "KEM_event"

# Server configuration for BungeeCord (specifies the bungee's config.yml server's name)

BungeeCord:
  lobbyServerName: "lobby"
  eventServerName: "event"

SpawnPoint:
  locX: 0
  locY: 0
  locZ: 0

Broadcast: "&9[EVENT {EventName}] &6{Broadcast} \n&epour participer faîtes &a/bmenu"