name: KanaEventManager
author: Kaname
version: 2.6.0
main: fr.kaname.kanaeventmanager.KanaEventManager
api-version: "1.16"
depend:
  - KanaBungeeTP
  - PlaceholderAPI
  - Vault

commands:
  manageevent:
    aliases:
      - event
      - e