name: KanaEventManager
author: Kaname
version: 2.0
main: fr.kaname.kanaeventmanager.KanaEventManager
depend:
  - KanaBungeeTP

commands:
  manageEvent:
    aliases:
      - event
      - e
    permission: kanaeventmanager.manage.event